"""添加 notice 表

Revision ID: 1a428296958f
Revises: b86971114dd1
Create Date: 2024-03-24 15:41:10.698292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a428296958f'
down_revision = 'b86971114dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False, comment='请假条 id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='发布者用户 id'),
    sa.Column('title', sa.String(length=30), nullable=True, comment='标题'),
    sa.Column('content', sa.String(length=255), nullable=True, comment='内容'),
    sa.Column('release_datetime', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='请假用户 id',
               existing_comment='用户 id',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户 id',
               existing_comment='请假用户 id',
               existing_nullable=True)

    op.drop_table('notice')
    # ### end Alembic commands ###
