"""公告添加状态字段

Revision ID: 2c03ec8c34f9
Revises: 1a428296958f
Create Date: 2024-03-27 11:38:52.978344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c03ec8c34f9'
down_revision = '1a428296958f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.SmallInteger(), nullable=True, comment='状态（0 不显示、1 显示）'))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               type_=sa.String(length=30),
               existing_comment='标题',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               existing_comment='标题',
               existing_nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
