"""notice 表添加 _type 字段

Revision ID: 8addac482c1b
Revises: 2c03ec8c34f9
Create Date: 2024-05-07 21:40:44.935345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8addac482c1b'
down_revision = '2c03ec8c34f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_type', sa.SmallInteger(), nullable=True, comment='通知类别（0 系统、1 学校、2 学院、3 辅导员）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('_type')

    # ### end Alembic commands ###
