"""管理员添加电话号码字段

Revision ID: b86971114dd1
Revises: 
Create Date: 2024-03-24 11:33:55.243894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86971114dd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telephone', sa.String(length=11), nullable=True, comment='电话号码'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('telephone')

    # ### end Alembic commands ###
