"""将所有教师的中英文改为辅导员

Revision ID: fca0f1613387
Revises: 8addac482c1b
Create Date: 2024-05-17 15:53:52.706395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fca0f1613387'
down_revision = '8addac482c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('teacher', 'assistant')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assistant_id', sa.Integer(), nullable=True, comment='辅导员 id'))
        batch_op.drop_constraint('student_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'assistant', ['assistant_id'], ['id'])
        batch_op.drop_column('teacher_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='教师 id'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_ibfk_2', 'teacher', ['teacher_id'], ['id'])
        batch_op.drop_column('assistant_id')

    op.rename_table('assistant', 'teacher')
    # ### end Alembic commands ###
