# Generated by Django 4.2.10 on 2024-02-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('role', models.CharField(choices=[(1, '学生'), (2, '辅导员'), (3, '管理员')], max_length=8, verbose_name='角色')),
                ('create_datetime', models.DateTimeField(verbose_name='创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('telephone', models.CharField(max_length=11, verbose_name='电话号码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('department', models.CharField(max_length=38, verbose_name='学部')),
                ('faculty', models.CharField(max_length=38, verbose_name='学院')),
                ('major', models.CharField(max_length=38, verbose_name='专业')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('_class', models.CharField(max_length=2, verbose_name='班级')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(1, '待审批'), (2, '已撤回'), (3, '审批中'), (4, '已驳回'), (5, '待销假'), (6, '销假中'), (7, '已完成')], max_length=8, verbose_name='请假条状态')),
                ('category', models.CharField(choices=[(1, '事假'), (2, '公假'), (3, '病假'), (4, '出校申请')], max_length=8, verbose_name='请假类型')),
                ('apply_timestamp', models.DateTimeField(verbose_name='申请时间')),
                ('start_timestamp', models.DateTimeField(verbose_name='开始时间')),
                ('end_timestamp', models.DateTimeField(verbose_name='结束时间')),
                ('annex_url', models.CharField(max_length=255, verbose_name='附件地址（图片/文件）')),
                ('leave_reason', models.TextField(verbose_name='请假原因')),
                ('reject_reason', models.TextField(verbose_name='驳回原因')),
                ('approver1_id', models.BigIntegerField(verbose_name='审批人 1 id')),
                ('a1_timestamp', models.DateTimeField(verbose_name='审批人 1 审批时间')),
                ('approver2_id', models.BigIntegerField(verbose_name='审批人 2 id')),
                ('a2_timestamp', models.DateTimeField(verbose_name='审批人 2 审批时间')),
                ('revoke_id', models.BigIntegerField(verbose_name='销假人 id')),
                ('revoke_timestamp', models.DateTimeField(verbose_name='销假时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
