# Generated by Django 4.2.10 on 2024-02-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
